[project]
name = 'voxcard-stacks'
description = 'VoxCard Savings - Community Savings & Rotating Credit on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.voxcard-savings-v5]
path = 'contracts/voxcard-savings-v5.clar'
clarity_version = 3
epoch = 'latest'

[contracts.voxcard-savings-v6]
path = 'contracts/voxcard-savings-v6.clar'
clarity_version = 3
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
